# Generated by Django 4.1 on 2022-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=250)),
                ('Calories', models.IntegerField(null=True)),
                ('TotalFat', models.IntegerField(null=True)),
                ('SaturatedFat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('TransFat', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Carbohydrates', models.IntegerField(null=True)),
                ('Protein', models.IntegerField(null=True)),
                ('Cholesterol', models.IntegerField(null=True)),
                ('Sodium', models.IntegerField(null=True)),
                ('DietaryFiber', models.IntegerField()),
                ('Sugars', models.IntegerField(null=True)),
                ('VitADaily', models.IntegerField(null=True)),
                ('VitCDaily', models.IntegerField(null=True)),
                ('CalciumDaily', models.IntegerField(null=True)),
                ('IronDaily', models.IntegerField(null=True)),
            ],
        ),
    ]
