# Generated by Django 4.1 on 2022-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='DietaryFiber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SaturatedFat',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
